/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriela.formulario;

/**
 *
 * @author SATC
 */
public class Enfermeira extends javax.swing.JFrame {

    /**
     * Creates new form Enfermeira
     */
    public Enfermeira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLblNome = new javax.swing.JLabel();
        jLblRG = new javax.swing.JLabel();
        jLblDataNascEnf = new javax.swing.JLabel();
        jLblCpfEnf = new javax.swing.JLabel();
        jLblSexoEnf = new javax.swing.JLabel();
        jLblEstadoCivilEnf = new javax.swing.JLabel();
        jLblEnderecoEnf = new javax.swing.JLabel();
        jLbltelefoneEnf = new javax.swing.JLabel();
        jLblCofen = new javax.swing.JLabel();
        jLblSetorEnf = new javax.swing.JLabel();
        jTxtNomeEnf = new javax.swing.JTextField();
        jTxtRG = new javax.swing.JTextField();
        jTxtCofen = new javax.swing.JTextField();
        jTxtSexoEnf = new javax.swing.JTextField();
        jTxtEnderecoEnf = new javax.swing.JTextField();
        jTxtDataNascEnf = new javax.swing.JTextField();
        jTxtCpfEnf = new javax.swing.JTextField();
        jTxtEstadoCivilEnf = new javax.swing.JTextField();
        jTxtTelefoneEnf = new javax.swing.JTextField();
        jTxtSetorEnf = new javax.swing.JTextField();
        jBtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("Enfermeiro (a)");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLblNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblNome.setText("Nome:");

        jLblRG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblRG.setText("RG:");

        jLblDataNascEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblDataNascEnf.setText("Data Nascimento:");

        jLblCpfEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblCpfEnf.setText("CPF:");

        jLblSexoEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblSexoEnf.setText("Sexo:");

        jLblEstadoCivilEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblEstadoCivilEnf.setText("Estado Civil:");

        jLblEnderecoEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblEnderecoEnf.setText("Endereço:");

        jLbltelefoneEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbltelefoneEnf.setText("Telefone:");

        jLblCofen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblCofen.setText("Cofen:");

        jLblSetorEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLblSetorEnf.setText("Setor:");

        jTxtNomeEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtRG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtCofen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtSexoEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtEnderecoEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtDataNascEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtCpfEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtEstadoCivilEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtTelefoneEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTxtSetorEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBtnSalvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtNomeEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblRG)
                                .addGap(47, 47, 47)
                                .addComponent(jTxtRG))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblSexoEnf)
                                .addGap(38, 38, 38)
                                .addComponent(jTxtSexoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbltelefoneEnf)
                                .addGap(61, 61, 61)
                                .addComponent(jTxtTelefoneEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblDataNascEnf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtDataNascEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCpfEnf)
                                .addGap(88, 88, 88)
                                .addComponent(jTxtCpfEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblEstadoCivilEnf)
                                .addGap(41, 41, 41)
                                .addComponent(jTxtEstadoCivilEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEnderecoEnf)
                            .addComponent(jLblCofen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCofen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEnderecoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLblSetorEnf)
                        .addGap(81, 81, 81)
                        .addComponent(jTxtSetorEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNome)
                    .addComponent(jLblDataNascEnf)
                    .addComponent(jTxtNomeEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDataNascEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRG)
                    .addComponent(jTxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTxtCpfEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblCpfEnf)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSexoEnf)
                    .addComponent(jLblEstadoCivilEnf)
                    .addComponent(jTxtSexoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstadoCivilEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEnderecoEnf)
                    .addComponent(jLbltelefoneEnf)
                    .addComponent(jTxtEnderecoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefoneEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCofen)
                    .addComponent(jLblSetorEnf)
                    .addComponent(jTxtCofen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSetorEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jBtnSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enfermeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblCofen;
    private javax.swing.JLabel jLblCpfEnf;
    private javax.swing.JLabel jLblDataNascEnf;
    private javax.swing.JLabel jLblEnderecoEnf;
    private javax.swing.JLabel jLblEstadoCivilEnf;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRG;
    private javax.swing.JLabel jLblSetorEnf;
    private javax.swing.JLabel jLblSexoEnf;
    private javax.swing.JLabel jLbltelefoneEnf;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtCofen;
    private javax.swing.JTextField jTxtCpfEnf;
    private javax.swing.JTextField jTxtDataNascEnf;
    private javax.swing.JTextField jTxtEnderecoEnf;
    private javax.swing.JTextField jTxtEstadoCivilEnf;
    private javax.swing.JTextField jTxtNomeEnf;
    private javax.swing.JTextField jTxtRG;
    private javax.swing.JTextField jTxtSetorEnf;
    private javax.swing.JTextField jTxtSexoEnf;
    private javax.swing.JTextField jTxtTelefoneEnf;
    // End of variables declaration//GEN-END:variables
}
