/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriela.formulario;

import br.com.gabriela.objeto.Enfermeira;
import br.com.gabriela.singleton.SEnfermeira;
import java.text.SimpleDateFormat;

/**
 *
 * @author SATC
 */
public class JFEnfermeira extends javax.swing.JFrame {

    /**
     * Creates new form Enfermeira
     */
    public JFEnfermeira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLNomeEnf = new javax.swing.JLabel();
        jLRGEnf = new javax.swing.JLabel();
        jLDataNascEnf = new javax.swing.JLabel();
        jLCpfEnf = new javax.swing.JLabel();
        jLSexoEnf = new javax.swing.JLabel();
        jLEstadoCivilEnf = new javax.swing.JLabel();
        jLEnderecoEnf = new javax.swing.JLabel();
        jLtelefoneEnf = new javax.swing.JLabel();
        jLCofen = new javax.swing.JLabel();
        jLSetorEnf = new javax.swing.JLabel();
        jTNomeEnf = new javax.swing.JTextField();
        jTRG = new javax.swing.JTextField();
        jTCofen = new javax.swing.JTextField();
        jTSexoEnf = new javax.swing.JTextField();
        jTEnderecoEnf = new javax.swing.JTextField();
        jTDataNascEnf = new javax.swing.JTextField();
        jTCpfEnf = new javax.swing.JTextField();
        jTEstadoCivilEnf = new javax.swing.JTextField();
        jTTelefoneEnf = new javax.swing.JTextField();
        jTSetorEnf = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("Enfermeiro (a)");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLNomeEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLNomeEnf.setText("Nome:");

        jLRGEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLRGEnf.setText("RG:");

        jLDataNascEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDataNascEnf.setText("Data Nascimento:");

        jLCpfEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCpfEnf.setText("CPF:");

        jLSexoEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLSexoEnf.setText("Sexo:");

        jLEstadoCivilEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEstadoCivilEnf.setText("Estado Civil:");

        jLEnderecoEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEnderecoEnf.setText("Endereço:");

        jLtelefoneEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLtelefoneEnf.setText("Telefone:");

        jLCofen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCofen.setText("Cofen:");

        jLSetorEnf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLSetorEnf.setText("Setor:");

        jTNomeEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTRG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTCofen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTSexoEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTEnderecoEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTDataNascEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTCpfEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTEstadoCivilEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTTelefoneEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTSetorEnf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLNomeEnf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTNomeEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLRGEnf)
                                    .addGap(47, 47, 47)
                                    .addComponent(jTRG))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLSexoEnf)
                                    .addGap(38, 38, 38)
                                    .addComponent(jTSexoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLEnderecoEnf))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLtelefoneEnf)
                                .addGap(61, 61, 61)
                                .addComponent(jTTelefoneEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDataNascEnf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTDataNascEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCpfEnf)
                                .addGap(88, 88, 88)
                                .addComponent(jTCpfEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEstadoCivilEnf)
                                .addGap(41, 41, 41)
                                .addComponent(jTEstadoCivilEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLCofen)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCofen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEnderecoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLSetorEnf)
                        .addGap(81, 81, 81)
                        .addComponent(jTSetorEnf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeEnf)
                    .addComponent(jLDataNascEnf)
                    .addComponent(jTNomeEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDataNascEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTCpfEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLCpfEnf))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLRGEnf)
                        .addComponent(jTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSexoEnf)
                    .addComponent(jLEstadoCivilEnf)
                    .addComponent(jTSexoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEstadoCivilEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEnderecoEnf)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLtelefoneEnf)
                        .addComponent(jTEnderecoEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTTelefoneEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCofen)
                    .addComponent(jLSetorEnf)
                    .addComponent(jTCofen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSetorEnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jBCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        Enfermeira Enf = null ;
        SimpleDateFormat adf = new SimpleDateFormat("dd/MM/yyyy");
        String nome = jTNomeEnf.getText();
        String cpf = jTCpfEnf.getText();
        String rg = jTRG.getText();
        int cofen = Integer.parseInt(jTCofen.getText());
        String endereco = jTEnderecoEnf.getText();
        String setor = jTSetorEnf.getText();
        String telefone = jTTelefoneEnf.getText();
        char sexo = jTSexoEnf.getText().toUpperCase().charAt(0);
        String EstadoCivil = jTEstadoCivilEnf.getText();
        
        
        SEnfermeira.getInstance().getEnfermeiras().add(Enf);

    }//GEN-LAST:event_jBCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEnfermeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JLabel jLCofen;
    private javax.swing.JLabel jLCpfEnf;
    private javax.swing.JLabel jLDataNascEnf;
    private javax.swing.JLabel jLEnderecoEnf;
    private javax.swing.JLabel jLEstadoCivilEnf;
    private javax.swing.JLabel jLNomeEnf;
    private javax.swing.JLabel jLRGEnf;
    private javax.swing.JLabel jLSetorEnf;
    private javax.swing.JLabel jLSexoEnf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLtelefoneEnf;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCofen;
    private javax.swing.JTextField jTCpfEnf;
    private javax.swing.JTextField jTDataNascEnf;
    private javax.swing.JTextField jTEnderecoEnf;
    private javax.swing.JTextField jTEstadoCivilEnf;
    private javax.swing.JTextField jTNomeEnf;
    private javax.swing.JTextField jTRG;
    private javax.swing.JTextField jTSetorEnf;
    private javax.swing.JTextField jTSexoEnf;
    private javax.swing.JTextField jTTelefoneEnf;
    // End of variables declaration//GEN-END:variables
}
