/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriela.formulario;

/**
 *
 * @author SATC
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public JFMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMAtestado = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenuItem();
        jMTriagem = new javax.swing.JMenuItem();
        jMenuItem = new javax.swing.JMenu();
        jMEnfermeira = new javax.swing.JMenuItem();
        jMMedico = new javax.swing.JMenuItem();
        jMPaciente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Procedimento");

        jMAtestado.setText("Atestado");
        jMAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtestadoActionPerformed(evt);
            }
        });
        jMenu3.add(jMAtestado);

        jMConsulta.setText("Consulta");
        jMConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaActionPerformed(evt);
            }
        });
        jMenu3.add(jMConsulta);

        jMTriagem.setText("Triagem");
        jMTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTriagemActionPerformed(evt);
            }
        });
        jMenu3.add(jMTriagem);

        jMenuBar2.add(jMenu3);

        jMenuItem.setText("Cadastrar");

        jMEnfermeira.setText("Enfermeira");
        jMEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEnfermeiraActionPerformed(evt);
            }
        });
        jMenuItem.add(jMEnfermeira);

        jMMedico.setText("Medico");
        jMMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMedicoActionPerformed(evt);
            }
        });
        jMenuItem.add(jMMedico);

        jMPaciente.setText("Paciente");
        jMPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPacienteActionPerformed(evt);
            }
        });
        jMenuItem.add(jMPaciente);

        jMenuBar2.add(jMenuItem);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtestadoActionPerformed
        JFAtestado atestado= new JFAtestado();
        atestado.setVisible(true);
    }//GEN-LAST:event_jMAtestadoActionPerformed

    private void jMConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaActionPerformed
        JFConsulta consulta = new JFConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_jMConsultaActionPerformed

    private void jMEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEnfermeiraActionPerformed
        JFEnfermeira enfermeira = new JFEnfermeira();
        enfermeira.setVisible(true);
    }//GEN-LAST:event_jMEnfermeiraActionPerformed

    private void jMMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMedicoActionPerformed
        JFMedico medico = new JFMedico();
        medico.setVisible(true);
    }//GEN-LAST:event_jMMedicoActionPerformed

    private void jMPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPacienteActionPerformed
        JFPaciente paciente = new JFPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_jMPacienteActionPerformed

    private void jMTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTriagemActionPerformed
        JFTriagem triagem = new JFTriagem();
        triagem.setVisible(true);
    }//GEN-LAST:event_jMTriagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMAtestado;
    private javax.swing.JMenuItem jMConsulta;
    private javax.swing.JMenuItem jMEnfermeira;
    private javax.swing.JMenuItem jMMedico;
    private javax.swing.JMenuItem jMPaciente;
    private javax.swing.JMenuItem jMTriagem;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuItem;
    // End of variables declaration//GEN-END:variables
}
