/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriela.formulario;

import br.com.gabriela.objeto.Medico;
import br.com.gabriela.singleton.SMedico;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JFMedico extends javax.swing.JFrame {

    /**
     * Creates new form Medico
     */
    public JFMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLNomeMed = new javax.swing.JLabel();
        jLDataNascMed = new javax.swing.JLabel();
        jLRgMed = new javax.swing.JLabel();
        jLCpfMed = new javax.swing.JLabel();
        jLEstadoCivilMed = new javax.swing.JLabel();
        jLSexoMed = new javax.swing.JLabel();
        jLEnderecoMed = new javax.swing.JLabel();
        jLTelefoneMed = new javax.swing.JLabel();
        jLCRM = new javax.swing.JLabel();
        jLEspecialidade = new javax.swing.JLabel();
        jLSetorMed = new javax.swing.JLabel();
        jTRgMed = new javax.swing.JTextField();
        jTNomeMed = new javax.swing.JTextField();
        jTSexomed = new javax.swing.JTextField();
        jTCRM = new javax.swing.JTextField();
        jTEnderecoMed = new javax.swing.JTextField();
        jTDataNascMed = new javax.swing.JTextField();
        jTEspecialidadeMed = new javax.swing.JTextField();
        jTCpfMed = new javax.swing.JTextField();
        jTEstadoCivilMed = new javax.swing.JTextField();
        jTTelefoneMed = new javax.swing.JTextField();
        jTSetorMed = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Médico (a)");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLNomeMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLNomeMed.setText("Nome:");

        jLDataNascMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDataNascMed.setText("Data de Nascimento:");

        jLRgMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLRgMed.setText("RG:");

        jLCpfMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCpfMed.setText("CPF:");

        jLEstadoCivilMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEstadoCivilMed.setText("Estado Civil:");

        jLSexoMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLSexoMed.setText("Sexo:");

        jLEnderecoMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEnderecoMed.setText("Endereço:");

        jLTelefoneMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLTelefoneMed.setText("Telefone:");

        jLCRM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCRM.setText("CRM:");

        jLEspecialidade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEspecialidade.setText("Especialidade:");

        jLSetorMed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLSetorMed.setText("Setor:");

        jTRgMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTNomeMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTSexomed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTCRM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTEnderecoMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTDataNascMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTEspecialidadeMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTCpfMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTEstadoCivilMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTTelefoneMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTSetorMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCRM)
                        .addGap(53, 53, 53)
                        .addComponent(jTCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLEnderecoMed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTEnderecoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLSexoMed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTSexomed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLRgMed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTRgMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLNomeMed)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLEspecialidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTEspecialidadeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDataNascMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jTDataNascMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCpfMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEstadoCivilMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTEstadoCivilMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTelefoneMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTTelefoneMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLSetorMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCadastrar)
                            .addComponent(jTSetorMed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeMed)
                    .addComponent(jLDataNascMed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDataNascMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRgMed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRgMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSexoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEstadoCivilMed, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSexomed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEstadoCivilMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTelefoneMed, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEnderecoMed)
                        .addComponent(jTEnderecoMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTTelefoneMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSetorMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSetorMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEspecialidadeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        Medico m = null ;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String nome = jTNomeMed.getText();
        String cpf = jTCpfMed.getText();
        String rg = jTRgMed.getText();
        int crm = Integer.parseInt(jTCRM.getText());
        String endereco = jTEnderecoMed.getText();
        String setor = jTSetorMed.getText();
        String telefone = jTTelefoneMed.getText();
        char sexo = jTSexomed.getText().toUpperCase().charAt(0);
        String especialidade = jTEspecialidadeMed.getText();
        String EstadoCivil = jTEstadoCivilMed.getText();
        
        SMedico.getInstance().getMedicos().add(m);
        
        try {
            Date jLDataNascMed = sdf.parse(jTDataNascMed.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(JFMedico.class.getName()).log(Level.SEVERE, rg,cpf);        }
                
    }//GEN-LAST:event_jBCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JLabel jLCRM;
    private javax.swing.JLabel jLCpfMed;
    private javax.swing.JLabel jLDataNascMed;
    private javax.swing.JLabel jLEnderecoMed;
    private javax.swing.JLabel jLEspecialidade;
    private javax.swing.JLabel jLEstadoCivilMed;
    private javax.swing.JLabel jLNomeMed;
    private javax.swing.JLabel jLRgMed;
    private javax.swing.JLabel jLSetorMed;
    private javax.swing.JLabel jLSexoMed;
    private javax.swing.JLabel jLTelefoneMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTCRM;
    private javax.swing.JTextField jTCpfMed;
    private javax.swing.JTextField jTDataNascMed;
    private javax.swing.JTextField jTEnderecoMed;
    private javax.swing.JTextField jTEspecialidadeMed;
    private javax.swing.JTextField jTEstadoCivilMed;
    private javax.swing.JTextField jTNomeMed;
    private javax.swing.JTextField jTRgMed;
    private javax.swing.JTextField jTSetorMed;
    private javax.swing.JTextField jTSexomed;
    private javax.swing.JTextField jTTelefoneMed;
    // End of variables declaration//GEN-END:variables
}
