/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriela.formulario;

import br.com.gabriela.objeto.Triagem;
import br.com.gabriela.singleton.SEnfermeira;
import br.com.gabriela.singleton.SPaciente;

/**
 *
 * @author SATC
 */
public class JFTriagem extends javax.swing.JFrame {

    /**
     * Creates new form Triagem
     */
    public JFTriagem() {
        initComponents();
        jTPacTriagem.setText(Integer.toString(SPaciente.getInstance().getPacientes().size()-1));
        jTPacTriagem.setEnabled(false);
        jTfebre.setEnabled(false);
        jTImc.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLEnferTriagem = new javax.swing.JLabel();
        jLPacTriagem = new javax.swing.JLabel();
        jLPressao = new javax.swing.JLabel();
        jLTemp = new javax.swing.JLabel();
        jLSintomas = new javax.swing.JLabel();
        jLAlergia = new javax.swing.JLabel();
        jLPeso = new javax.swing.JLabel();
        jLAltura = new javax.swing.JLabel();
        jLImc = new javax.swing.JLabel();
        jLFebre = new javax.swing.JLabel();
        jTEnfTriagem = new javax.swing.JTextField();
        jTPacTriagem = new javax.swing.JTextField();
        jTPressao = new javax.swing.JTextField();
        jTTemperatura = new javax.swing.JTextField();
        jTSintomas = new javax.swing.JTextField();
        jTPeso = new javax.swing.JTextField();
        jTImc = new javax.swing.JTextField();
        jTfebre = new javax.swing.JTextField();
        jTAlergias = new javax.swing.JTextField();
        jTAltura = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Triagem");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLEnferTriagem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEnferTriagem.setText("Enfermeira:");

        jLPacTriagem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLPacTriagem.setText("Paciente:");

        jLPressao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLPressao.setText("Pressão:");

        jLTemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLTemp.setText("Temperatura:");

        jLSintomas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLSintomas.setText("Sintomas:");

        jLAlergia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLAlergia.setText("Alergias:");

        jLPeso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLPeso.setText("Peso:");

        jLAltura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLAltura.setText("Altura:");

        jLImc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLImc.setText("IMC:");

        jLFebre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLFebre.setText("Febre:");

        jTEnfTriagem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTPacTriagem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTPressao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTTemperatura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTSintomas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTPeso.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTImc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTfebre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTAlergias.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTAltura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLImc)
                            .addComponent(jLPeso)
                            .addComponent(jLSintomas))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTImc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLAltura)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jBSalvar)
                                                .addGap(28, 28, 28))
                                            .addComponent(jTAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLFebre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTfebre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLAlergia)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(45, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLEnferTriagem)
                                    .addComponent(jLPacTriagem)
                                    .addComponent(jLPressao))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTPressao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPacTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTEnfTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEnferTriagem)
                    .addComponent(jTEnfTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPacTriagem)
                    .addComponent(jTPacTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPressao)
                    .addComponent(jTPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLTemp)
                                    .addComponent(jTTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTfebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSintomas)
                            .addComponent(jLAlergia)
                            .addComponent(jTSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPeso)
                            .addComponent(jLAltura)
                            .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLImc)
                            .addComponent(jTImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSalvar)))
                    .addComponent(jLFebre))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        for(int i =0; i<SEnfermeira.getInstance().getEnfermeiras().size(); i++){
          jTEnfTriagem.getText(); 
          jTEnfTriagem.setEnabled(false);
     }    
              
                
    }//GEN-LAST:event_jBSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTriagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLAlergia;
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLEnferTriagem;
    private javax.swing.JLabel jLFebre;
    private javax.swing.JLabel jLImc;
    private javax.swing.JLabel jLPacTriagem;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLPressao;
    private javax.swing.JLabel jLSintomas;
    private javax.swing.JLabel jLTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTAlergias;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTEnfTriagem;
    private javax.swing.JTextField jTImc;
    private javax.swing.JTextField jTPacTriagem;
    private javax.swing.JTextField jTPeso;
    private javax.swing.JTextField jTPressao;
    private javax.swing.JTextField jTSintomas;
    private javax.swing.JTextField jTTemperatura;
    private javax.swing.JTextField jTfebre;
    // End of variables declaration//GEN-END:variables
}
